# This workflow will build and test a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "Go"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: "Build & Test"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        dir:
          - "./cmd/psygometry"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Set up Go"
        uses: "actions/setup-go@v5"
        with:
          go-version-file: "${{ matrix.dir }}/go.mod"
          cache-dependency-path: "${{ matrix.dir }}/go.sum"

      - name: "Install Dependencies"
        working-directory: "${{ matrix.dir }}"
        run: |
          go get .

      - name: "Build"
        working-directory: "${{ matrix.dir }}"
        run: |
          go build -v .

      - name: "Test"
        working-directory: "${{ matrix.dir }}"
        run: |
          go test -v . -quickchecks 10000
